#!/bin/sh
# Copyright (C) 2004-2005 Intel Corporation
#
MODULE=ipw2100
if [ `whoami` != "root" ]; then
	echo "You must be root to run this script."
	return
fi

unset UNLOADED
for i in ${MODULE} ieee80211 ieee80211_crypt_wep ieee80211_crypt_tkip ieee80211_crypt_ccmp ieee80211_crypt ; do
	if lsmod | grep -q $i; then
		UNLOADED="${UNLOADED}${i} "
		rmmod $i
	fi
done
if [ -z "${UNLOADED}" ]; then
	echo "No modules unloaded."
else
	echo "Unloaded: $UNLOADED"
fi
